DELETE http://localhost:3000/posts/5

###
GET http://localhost:3000/categories

###
GET http://localhost:3000/posts

###

POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "Post 17",
  "body": "Body of post 17",
  "category_id": 3
}

###
GET http://localhost:3000/users

###

POST http://localhost:3000/blueadasdasd

###

GET http://localhost:3000/users/mike

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Baba",
  "password": "secret458"
}

###

POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "Baba",
  "password": "secret458"
}
###

POST http://localhost:3000/validate
Content-Type: application/json

{
  "email":"james@james.com",
  "town":"Kaunas",
  "age":28,
  "gender":"male"
}