GET http://localhost:3000/users

###

POST http://localhost:3000/blueadasdasd

###

GET http://localhost:3000/users/mike

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Mike",
  "password": "secret123"
}

###

POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "Mikes",
  "password": "secret123"
}
###

POST http://localhost:3000/validate
Content-Type: application/json

{
  "email":"james@james.com",
  "town":"Kaunas",
  "age":28,
  "gender":"male"
}