DELETE http://localhost:3000/posts/5

###
GET http://localhost:3000/categories

###
GET http://localhost:3000/posts

###

POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJhYmEiLCJpYXQiOjE2NDY3NDYwMTksImV4cCI6MTY0Njc0OTYxOX0.s3rCWiQSE_ag7WftGtCFc9GPN7BZfnjyWYWV-eL4BuE

{
  "title": "Post 33",
  "body": "Body of post 33",
  "category_id": 3
}

###
GET http://localhost:3000/users

###

POST http://localhost:3000/blueadasdasd

###

GET http://localhost:3000/users/mike

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Baba",
  "password": "secret458"
}

###

POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "Baba",
  "password": "secret458"
}
###

POST http://localhost:3000/validate
Content-Type: application/json

{
  "email":"james@james.com",
  "town":"Kaunas",
  "age":28,
  "gender":"male"
}